config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'main_pages#home'
  get '/signin', to: 'sessions#new'
  post '/signin', to: 'sessions#create'
  delete '/signout', to: 'sessions#destroy'
  resources :posts, only: [:new, :create, :index]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  validates :title, :body, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  has_many :posts
  before_create :create_token
  validates :username, :email, presence: true, uniqueness: { case_sensitive: false }
  has_secure_password
  validates :password, presence: true, length: { minimum: 6, maximum: 20 }

 def create_token
  if self.remember_digest.nil?
    self.remember_digest = Digest::SHA1.hexdigest(SecureRandom.urlsafe_base64)
  else
    update_attribute(:remember_digest, Digest::SHA1.hexdigest(SecureRandom.urlsafe_base64))
  end
 end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include SessionsHelper
end

app/controllers/main_pages_controller.rb
class MainPagesController < ApplicationController
  def home 
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :logged_in?

  def new
  end

  def create
    post = Post.new(title: params[:post][:title], body: params[:post][:body], user_id: @current_user.id)
    if post.save
      flash[:success] = 'Post created!'
      redirect_to posts_path
    else
      flash.now[:error] = 'Invalid post fields'
      render 'new'
    end
  end

  def index
    @posts = Post.all.reverse
  end

  private

    def post_params
      params.require(:post).permit(:title, :body)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email])
    if user && user.authenticate(params[:session][:password])
      sign_in(user)
      redirect_to root_path
    else
      flash.now[:error] = 'Invalid account information'
      render 'new'
    end
  end

  def destroy
    sign_out
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def title(page_title = '')
    base_title = 'Elitium'
    base_title + ' | ' + page_title
  end
end

app/helpers/main_pages_helper.rb
module MainPagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def sign_in(user)
    user.create_token
    cookies.permanent[:token_digest] = user.remember_digest
  end

  def get_user
    if cookies[:token_digest]
      @current_user ||= User.find_by(remember_digest: cookies[:token_digest])
    end
  end

  def sign_out
    cookies.delete(:token_digest)
    redirect_to root_path
  end

  def logged_in?
    !get_user.nil?
  end
end

app/views/layouts/_header.html.erb
<div>
	<div class="header">
		<a href="<%= root_path %>">Home</a>
		<% if logged_in? %>
			<%= link_to 'Sign out', signout_path, method: :delete %>
		<% else %>
			<%= link_to 'Sign in', signin_path %>
		<% end %>
	</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= title(yield(:title)) %></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <div>
      <% flash.each do |type, msg| %>
        <div class="<%= type %>"> 
          <p><%= msg %></p>
        </div>
      <% end %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/main_pages/home.html.erb
<% provide(:title, 'Home') %>

<div class="main">
	<h1>Welcome to Elitium<% if logged_in? %>, <%= @current_user.username %> <% end %></h1>

<p class="links"><%= link_to "View posts", posts_path, class: 'btn' %></p>
<% if logged_in? %>
	<p class="links"><%= link_to 'New post', new_post_path %></p>
<% end %>
</div>

app/views/posts/index.html.erb
<% provide(:title, 'All posts') %>
<div class="main">
	<h1>All posts</h1>
	<p class="links"><%= link_to 'New post', new_post_path %></p>
	<div class="posts">
	<% @posts.each do |p| %>
		<div class="post">
			<p class="title"><%= p.title %></p>
			<% if logged_in? %>
				<p class="byline">by <%= p.user.username %></p>
			<% end %>
			<p class='body'><%= p.body %></p>
			<p><%= time_ago_in_words(p.created_at) %></p>
		</div>
	<% end %>
	</div>
</div>

app/views/posts/new.html.erb
<% provide(:title, 'New Post') %>

<div class="main">
	<h1>New Post</h1>
	<div class="form">
		<%= form_for :post, url: posts_path do |f| %>
			<%= f.label :title, class: 'label' %><br>
			<%= f.text_field :title, class: 'field' %><br>

			<%= f.label :body, class: 'label'%><br>
			<%= f.text_area :body, class: 'text_area'%><br>

			<%= f.submit 'Post', class: 'btn'%>
		<% end %>
	</div>
</div>